
ignored = ["github.com/Sirupsen/logrus"]

[prune]
  go-tests = true
  unused-packages = true


[[constraint]]
    name = "github.com/spf13/cobra"
    version = "0.0.3"

[[constraint]]
    name = "github.com/spf13/viper"
    version = "1.3.1"

[[constraint]]
    name = "github.com/sirupsen/logrus"
    version = "1.2.0"

[[constraint]]
    name = "github.com/meatballhat/negroni-logrus"
    revision = "31067281800f66f57548a7a32d9c6c5f963fef83"

[[constraint]]
    name = "github.com/x-cray/logrus-prefixed-formatter"
    version = "0.5.2"

[[constraint]]
    name = "github.com/urfave/negroni"
    version = "1.0.0"

[[constraint]]
    name = "github.com/gorilla/mux"
    version = "1.6.2"

[[constraint]]
    name = "github.com/gorilla/handlers"
    version = "1.4.0"

[[constraint]]
    name = "github.com/thoas/stats"
    revision = "fc5c06ed3df0e436bc483ccc97053cd98930ca61"

[[constraint]]
    name = "github.com/DataDog/datadog-go"
    version = "2.1.0"

[[constraint]]
    name = "github.com/satori/go.uuid"
    revision = "b2ce2384e17bbe0c6d34077efa39dbab3e09123b"

[[constraint]]
    name = "github.com/vulcand/oxy"
    revision = "c34b0c501e43223bc816ac9b40b0ac29c44c8952"

[[constraint]]
    name = "github.com/aws/aws-sdk-go-v2"
    version = "0.6.0"
